### ISSUE TITLE
Feature Request: Add github actions for typo check linter 

### ISSUE THREAD

**Issue by moonD4rk** [moonD4rk/HackBrowserData#283]
## Feature Description

[typos-check](https://github.com/crate-ci/typos) GitHub Actions

```yaml
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling with custom config file
        uses: crate-ci/typos@v1.16.10
        with:
          config: ./typos.toml
```

## Why is this feature needed?

Avoid typos.

## Checklist
- [x] I have checked the [existing issues](https://github.com/moonD4rk/HackBrowserData/issues) for similar problems.

## Screenshots/Videos
If applicable, add screenshots or videos to help explain your proposal.
